set(my_cpp_files
cpp/imageloader.cpp
cpp/dataserver.hpp
cpp/datautil.hpp
cpp/unsafearea.hpp
cpp/applicationui.hpp
cpp/uiconstants.hpp
cpp/gen/SessionTrack.cpp
cpp/gen/Day.hpp
cpp/gen/SessionLists.hpp
cpp/gen/SpeakerImage.cpp
cpp/gen/PersonsAPI.hpp
cpp/gen/SessionAPI.cpp
cpp/gen/Favorite.cpp
cpp/gen/Speaker.cpp
cpp/gen/Room.hpp
cpp/gen/DataManager.cpp
cpp/gen/Session.hpp
cpp/gen/SpeakerAPI.hpp
cpp/gen/SettingsData.hpp
cpp/gen/Conference.hpp
cpp/gen/SessionTrackAPI.cpp
cpp/gen/Room.cpp
cpp/gen/DataManager.hpp
cpp/gen/Session.cpp
cpp/gen/SpeakerAPI.cpp
cpp/gen/Conference.cpp
cpp/gen/SettingsData.cpp
cpp/gen/SessionTrackAPI.hpp
cpp/gen/Day.cpp
cpp/gen/SessionTrack.hpp
cpp/gen/SessionLists.cpp
cpp/gen/SpeakerImage.hpp
cpp/gen/PersonsAPI.cpp
cpp/gen/SessionAPI.hpp
cpp/gen/Favorite.hpp
cpp/gen/Speaker.hpp
cpp/unsafearea.cpp
cpp/applicationui.cpp
cpp/imageloader.hpp
cpp/qml_singleton.h
cpp/dataserver.cpp
cpp/datautil.cpp
)
