set(my_qml_files
qml/tabs/TabButtonTextAndIcon.qml
qml/tabs/TextTabBar.qml
qml/tabs/TabButtonIcon.qml
qml/tabs/ScheduleTabBar.qml
qml/navigation/DrawerFavoritesNavigationBar.qml
qml/navigation/Destination.qml
qml/navigation/DrawerNavigationButton.qml
qml/navigation/SpeakerNavigation.qml
qml/navigation/DrawerFavoritesNavigationButton.qml
qml/navigation/DrawerFavoritesMenuButton.qml
qml/navigation/RoomsNavigation.qml
qml/navigation/ScheduleNavigation.qml
qml/navigation/DrawerNavigationTextButton.qml
qml/navigation/TrackNavigation.qml
qml/navigation/DrawerTitleBar.qml
qml/navigation/DrawerSubtitle.qml
qml/navigation/VenueNavigation.qml
qml/navigation/DrawerNavigationBar.qml
qml/navigation/DrawerDivider.qml
qml/Main.qml
qml/common/IconColored.qml
qml/common/CommunicationMenu.qml
qml/common/LabelDisplay4.qml
qml/common/CommunicationButton.qml
qml/common/ListRowButton.qml
qml/common/IconInactive.qml
qml/common/ComboBoxModal.qml
qml/common/ComboBoxWithIcon.qml
qml/common/LabelDisplay3.qml
qml/common/FooterCancelSave.qml
qml/common/IconOnPrimary.qml
qml/common/LabelDisplay2.qml
qml/common/LabelDisplay1.qml
qml/common/SwipeTextTitle.qml
qml/common/LabelCaption.qml
qml/common/CharButton.qml
qml/common/HorizontalListDivider.qml
qml/common/LabelBodySecondary.qml
qml/common/TextFieldInt.qml
qml/common/ButtonFlat.qml
qml/common/SimpleTextTitle.qml
qml/common/LabelTitle.qml
qml/common/ButtonOneChar.qml
qml/common/VerticalDivider.qml
qml/common/ButtonRaised.qml
qml/common/IconOnAccent.qml
qml/common/ButtonOneCharUncolored.qml
qml/common/IconActive.qml
qml/common/LabelSubheading.qml
qml/common/DotMarker.qml
qml/common/SwitchWithLeftLabel.qml
qml/common/FloatingActionMiniButton.qml
qml/common/MenuItemWithIcon.qml
qml/common/LabelHeadline.qml
qml/common/TextFieldDecimal.qml
qml/common/CharCircle.qml
qml/common/ComboBoxButton.qml
qml/common/HorizontalDivider.qml
qml/common/FloatingActionButton.qml
qml/common/ButtonIconActive.qml
qml/common/SearchTextPane.qml
qml/common/MenuItemWithDot.qml
qml/common/StackTextTitle.qml
qml/common/TextFieldDoubleInt.qml
qml/common/TextAreaRow.qml
qml/common/LabelBody.qml
qml/popups/PopupExit.qml
qml/popups/TimePicker.qml
qml/popups/LetterPicker.qml
qml/popups/DatePicker.qml
qml/popups/PopupUpdate.qml
qml/popups/PopupInfo.qml
qml/popups/PopupNetworkInfo.qml
qml/popups/PopupToast.qml
qml/popups/PopupError.qml
qml/popups/PopupOK.qml
qml/pages/TrackListPage.qml
qml/pages/AboutPage.qml
qml/pages/DayPage.qml
qml/pages/SessionListView.qml
qml/pages/AccentColorPage.qml
qml/pages/RoomListPage.qml
qml/pages/VenuePage.qml
qml/pages/SpeakerImageDetailPage.qml
qml/pages/DaySwiper.qml
qml/pages/HomePage.qml
qml/pages/SessionDetailPage.qml
qml/pages/RoomDetailPage.qml
qml/pages/PrimaryColorPage.qml
qml/pages/SpeakerListPage.qml
qml/pages/InitialItemPage.qml
qml/pages/MySchedulePage.qml
qml/pages/TrackSessionListPage.qml
qml/pages/RoomSessionListPage.qml
qml/pages/HelpRow.qml
qml/pages/HelpPage.qml
qml/pages/SpeakerImageItem.qml
qml/pages/SpeakerDetailPage.qml
)
